package jim.omerspi.model;
// Generated Jun 6, 2013 3:43:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Carrequisitionservice generated by hbm2java
 */
public class Carrequisitionservice  implements java.io.Serializable {


     private Integer carServiceId;
     private Vendor vendor;
     private Carregistration carregistration;
     private Employee employee;
     private Carrequisition carrequisition;
     private String numberPlate;
     private String driverNames;
     private String note;
     private Date exactTimeOfReturn;
     private Date servedOn;
     private String serviceNumber;

    public Carrequisitionservice() {
    }

	
    public Carrequisitionservice(Carrequisition carrequisition) {
        this.carrequisition = carrequisition;
    }
    public Carrequisitionservice(Vendor vendor, Carregistration carregistration, Employee employee, Carrequisition carrequisition, String numberPlate, String driverNames, String note, Date exactTimeOfReturn,Date servedOn,String serviceNumber) {
       this.vendor = vendor;
       this.carregistration = carregistration;
       this.employee = employee;
       this.carrequisition = carrequisition;
       this.numberPlate = numberPlate;
       this.driverNames = driverNames;
       this.note = note;
       this.exactTimeOfReturn = exactTimeOfReturn;
       this.servedOn = servedOn;
       this.serviceNumber=serviceNumber;
    }
   
    public Integer getCarServiceId() {
        return this.carServiceId;
    }
    
    public void setCarServiceId(Integer carServiceId) {
        this.carServiceId = carServiceId;
    }
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }
    public Carregistration getCarregistration() {
        return this.carregistration;
    }
    
    public void setCarregistration(Carregistration carregistration) {
        this.carregistration = carregistration;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Carrequisition getCarrequisition() {
        return this.carrequisition;
    }
    
    public void setCarrequisition(Carrequisition carrequisition) {
        this.carrequisition = carrequisition;
    }
    public String getNumberPlate() {
        return this.numberPlate;
    }
    
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate;
    }
    public String getDriverNames() {
        return this.driverNames;
    }
    
    public void setDriverNames(String driverNames) {
        this.driverNames = driverNames;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getExactTimeOfReturn() {
        return this.exactTimeOfReturn;
    }
    
    public void setExactTimeOfReturn(Date exactTimeOfReturn) {
        this.exactTimeOfReturn = exactTimeOfReturn;
    }
    public Date getServedOn() {
        return this.servedOn;
    }

    public void setServedOn(Date servedOn) {
        this.servedOn = servedOn;
    }

     public String getServiceNumber() {
        return serviceNumber;
    }

    public void setServiceNumber(String serviceNumber) {
        this.serviceNumber = serviceNumber;
    }
    


}


