package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carrequisition generated by hbm2java
 */
public class Carrequisition  implements java.io.Serializable {


     private Integer carRequisitionId;
     private Employee employee;
     private Cartype cartype;
     private String reason;
     private String destination;
     private Date departureTime;
     private Date expectedTimeReturn;
     private Date requestedOn;
     private String carRequisitionStatus;
     private Date servedOn;
     private Integer baggageWeight;
     private Integer totalAmount;
     private String destinationType;
     private String costingBasis;
     private Boolean seen;
     private Set<Carrequisitionservice> carrequisitionservices = new HashSet<Carrequisitionservice>(0);
     private Set<Requisitionresponses> requisitionresponseses = new HashSet<Requisitionresponses>(0);
     private Set<Itenerary> iteneraries = new HashSet<Itenerary>(0);
     private Set<Memo> memos = new HashSet<Memo>(0);
     private Set<Itenerary> iteneraries_1 = new HashSet<Itenerary>(0);
     private Set<Carrequisitionservice> carrequisitionservices_1 = new HashSet<Carrequisitionservice>(0);

    public Carrequisition() {
    }

	
    public Carrequisition(Employee employee, String reason, String destination, Date departureTime, Date expectedTimeReturn, Date requestedOn) {
        this.employee = employee;
        this.reason = reason;
        this.destination = destination;
        this.departureTime = departureTime;
        this.expectedTimeReturn = expectedTimeReturn;
        this.requestedOn = requestedOn;
    }
    public Carrequisition(Employee employee, Cartype cartype, String reason, String destination, Date departureTime, Date expectedTimeReturn, Date requestedOn, String carRequisitionStatus, Date servedOn, Integer baggageWeight, Integer totalAmount, String destinationType, String costingBasis, Boolean seen, Set<Carrequisitionservice> carrequisitionservices, Set<Requisitionresponses> requisitionresponseses, Set<Itenerary> iteneraries, Set<Memo> memos, Set<Itenerary> iteneraries_1, Set<Carrequisitionservice> carrequisitionservices_1) {
       this.employee = employee;
       this.cartype = cartype;
       this.reason = reason;
       this.destination = destination;
       this.departureTime = departureTime;
       this.expectedTimeReturn = expectedTimeReturn;
       this.requestedOn = requestedOn;
       this.carRequisitionStatus = carRequisitionStatus;
       this.servedOn = servedOn;
       this.baggageWeight = baggageWeight;
       this.totalAmount = totalAmount;
       this.destinationType = destinationType;
       this.costingBasis = costingBasis;
       this.seen = seen;
       this.carrequisitionservices = carrequisitionservices;
       this.requisitionresponseses = requisitionresponseses;
       this.iteneraries = iteneraries;
       this.memos = memos;
       this.iteneraries_1 = iteneraries_1;
       this.carrequisitionservices_1 = carrequisitionservices_1;
    }
   
    public Integer getCarRequisitionId() {
        return this.carRequisitionId;
    }
    
    public void setCarRequisitionId(Integer carRequisitionId) {
        this.carRequisitionId = carRequisitionId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Cartype getCartype() {
        return this.cartype;
    }
    
    public void setCartype(Cartype cartype) {
        this.cartype = cartype;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public Date getDepartureTime() {
        return this.departureTime;
    }
    
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }
    public Date getExpectedTimeReturn() {
        return this.expectedTimeReturn;
    }
    
    public void setExpectedTimeReturn(Date expectedTimeReturn) {
        this.expectedTimeReturn = expectedTimeReturn;
    }
    public Date getRequestedOn() {
        return this.requestedOn;
    }
    
    public void setRequestedOn(Date requestedOn) {
        this.requestedOn = requestedOn;
    }
    public String getCarRequisitionStatus() {
        return this.carRequisitionStatus;
    }
    
    public void setCarRequisitionStatus(String carRequisitionStatus) {
        this.carRequisitionStatus = carRequisitionStatus;
    }
    public Date getServedOn() {
        return this.servedOn;
    }
    
    public void setServedOn(Date servedOn) {
        this.servedOn = servedOn;
    }
    public Integer getBaggageWeight() {
        return this.baggageWeight;
    }
    
    public void setBaggageWeight(Integer baggageWeight) {
        this.baggageWeight = baggageWeight;
    }
    public Integer getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getDestinationType() {
        return this.destinationType;
    }
    
    public void setDestinationType(String destinationType) {
        this.destinationType = destinationType;
    }
    public String getCostingBasis() {
        return this.costingBasis;
    }
    
    public void setCostingBasis(String costingBasis) {
        this.costingBasis = costingBasis;
    }
    public Boolean getSeen() {
        return this.seen;
    }
    
    public void setSeen(Boolean seen) {
        this.seen = seen;
    }
    public Set<Carrequisitionservice> getCarrequisitionservices() {
        return this.carrequisitionservices;
    }
    
    public void setCarrequisitionservices(Set<Carrequisitionservice> carrequisitionservices) {
        this.carrequisitionservices = carrequisitionservices;
    }
    public Set<Requisitionresponses> getRequisitionresponseses() {
        return this.requisitionresponseses;
    }
    
    public void setRequisitionresponseses(Set<Requisitionresponses> requisitionresponseses) {
        this.requisitionresponseses = requisitionresponseses;
    }
    public Set<Itenerary> getIteneraries() {
        return this.iteneraries;
    }
    
    public void setIteneraries(Set<Itenerary> iteneraries) {
        this.iteneraries = iteneraries;
    }
    public Set<Memo> getMemos() {
        return this.memos;
    }
    
    public void setMemos(Set<Memo> memos) {
        this.memos = memos;
    }
    public Set<Itenerary> getIteneraries_1() {
        return this.iteneraries_1;
    }
    
    public void setIteneraries_1(Set<Itenerary> iteneraries_1) {
        this.iteneraries_1 = iteneraries_1;
    }
    public Set<Carrequisitionservice> getCarrequisitionservices_1() {
        return this.carrequisitionservices_1;
    }
    
    public void setCarrequisitionservices_1(Set<Carrequisitionservice> carrequisitionservices_1) {
        this.carrequisitionservices_1 = carrequisitionservices_1;
    }




}


