package jim.omerspi.model;
// Generated Jun 6, 2013 3:43:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cartype generated by hbm2java
 */
public class Cartype  implements java.io.Serializable {


     private Integer carTypeId;
     private String typeName;
     private int dailyCost;
     private int hourlyCost;
     private Set<Carrequisition> carrequisitions = new HashSet<Carrequisition>(0);

    public Cartype() {
    }

	
    public Cartype(String typeName) {
        this.typeName = typeName;
    }
    public Cartype(String typeName, int dailyCost, int hourlyCost, Set<Carrequisition> carrequisitions) {
       this.typeName = typeName;
       this.dailyCost = dailyCost;
       this.hourlyCost = hourlyCost;
       this.carrequisitions = carrequisitions;
    }
   
    public Integer getCarTypeId() {
        return this.carTypeId;
    }
    
    public void setCarTypeId(Integer carTypeId) {
        this.carTypeId = carTypeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public int getDailyCost() {
        return this.dailyCost;
    }
    
    public void setDailyCost(int dailyCost) {
        this.dailyCost = dailyCost;
    }
    public int getHourlyCost() {
        return this.hourlyCost;
    }
    
    public void setHourlyCost(int hourlyCost) {
        this.hourlyCost = hourlyCost;
    }
    public Set<Carrequisition> getCarrequisitions() {
        return this.carrequisitions;
    }
    
    public void setCarrequisitions(Set<Carrequisition> carrequisitions) {
        this.carrequisitions = carrequisitions;
    }




}


