package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categorytype generated by hbm2java
 */
public class Categorytype  implements java.io.Serializable {


     private Integer categoryTypeId;
     private Category category;
     private String categoryTypeName;
     private Set<Items> itemses = new HashSet<Items>(0);

    public Categorytype() {
    }

	
    public Categorytype(Category category, String categoryTypeName) {
        this.category = category;
        this.categoryTypeName = categoryTypeName;
    }
    public Categorytype(Category category, String categoryTypeName, Set<Items> itemses) {
       this.category = category;
       this.categoryTypeName = categoryTypeName;
       this.itemses = itemses;
    }
   
    public Integer getCategoryTypeId() {
        return this.categoryTypeId;
    }
    
    public void setCategoryTypeId(Integer categoryTypeId) {
        this.categoryTypeId = categoryTypeId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getCategoryTypeName() {
        return this.categoryTypeName;
    }
    
    public void setCategoryTypeName(String categoryTypeName) {
        this.categoryTypeName = categoryTypeName;
    }
    public Set<Items> getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set<Items> itemses) {
        this.itemses = itemses;
    }




}


