package jim.omerspi.model;
// Generated May 14, 2013 4:28:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer departmentRegistrationId;
     private String departmentCode;
     private String departmentName;
     private String functionalLocation;
    
     private Set<Employee> employees = new HashSet<Employee>(0);
     
     private Set<Employee> employees_1 = new HashSet<Employee>(0);

    public Department() {
    }

	
    public Department(String departmentCode, String departmentName, String functionalLocation) {
        this.departmentCode = departmentCode;
        this.departmentName = departmentName;
        this.functionalLocation = functionalLocation;
    }
    public Department(String departmentCode, String departmentName, String functionalLocation, Set<Employee> employees, Set<Employee> employees_1) {
       this.departmentCode = departmentCode;
       this.departmentName = departmentName;
       this.functionalLocation = functionalLocation;
       
       this.employees = employees;
      
       this.employees_1 = employees_1;
    }
   
    public Integer getDepartmentRegistrationId() {
        return this.departmentRegistrationId;
    }
    
    public void setDepartmentRegistrationId(Integer departmentRegistrationId) {
        this.departmentRegistrationId = departmentRegistrationId;
    }
    public String getDepartmentCode() {
        return this.departmentCode;
    }
    
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public String getFunctionalLocation() {
        return this.functionalLocation;
    }
    
    public void setFunctionalLocation(String functionalLocation) {
        this.functionalLocation = functionalLocation;
    }
  
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }
   
    public Set<Employee> getEmployees_1() {
        return this.employees_1;
    }
    
    public void setEmployees_1(Set<Employee> employees_1) {
        this.employees_1 = employees_1;
    }




}


