package jim.omerspi.model;
// Generated Sep 2, 2013 11:37:18 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer employeeRegistrationId;
     private Department department;
     private String employeeCode;
     private String firstName;
     private String lastName;
     private String gender;
     private String jobPosition;
     private String nationalId;
     private String telephone;
     private String identificationWord;
     private String state;
     private Date firstDate;
     private Date changePositionDate;
     private Date innactiveDate;
     private Boolean driver;
     private String licenceNumber;
     private String workEmail;
     private Set<User> users = new HashSet<User>(0);
     private Set<Carrequisitionservice> carrequisitionservices = new HashSet<Carrequisitionservice>(0);
     private Set<Officeassetrequisition> officeassetrequisitions = new HashSet<Officeassetrequisition>(0);
     private Set<Requisitionresponses> requisitionresponsesesForHodEmployeeRegistrationId = new HashSet<Requisitionresponses>(0);
     private Set<Stationaryregistration> stationaryregistrations = new HashSet<Stationaryregistration>(0);
     private Set<Stationaryrequisition> stationaryrequisitions = new HashSet<Stationaryrequisition>(0);
     private Set<User> users_1 = new HashSet<User>(0);
     private Set<Carrequisitionservice> carrequisitionservices_1 = new HashSet<Carrequisitionservice>(0);
     private Set<Officeassetrequisition> officeassetrequisitions_1 = new HashSet<Officeassetrequisition>(0);
     private Set<Carrequisition> carrequisitions = new HashSet<Carrequisition>(0);
     private Set<Requisitionresponses> requisitionresponsesesForLogisticEmployeeRegistrationId = new HashSet<Requisitionresponses>(0);
     private Set<Carrequisition> carrequisitions_1 = new HashSet<Carrequisition>(0);
     private Set<Stationaryrequisition> stationaryrequisitions_1 = new HashSet<Stationaryrequisition>(0);
     private Set<Requisitionresponses> requisitionresponsesesForDafEmployeeRegistrationId = new HashSet<Requisitionresponses>(0);

    public Employee() {
    }

	
    public Employee(String employeeCode, String firstName, String lastName, String gender, String jobPosition, String nationalId, String identificationWord) {
        this.employeeCode = employeeCode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.jobPosition = jobPosition;
        this.nationalId = nationalId;
        this.identificationWord = identificationWord;
    }
    public Employee(Department department, String employeeCode, String firstName, String lastName, String gender, String jobPosition, String nationalId, String telephone, String identificationWord, String state, Date firstDate, Date changePositionDate, Date innactiveDate, Boolean driver, String licenceNumber, String workEmail, Set<User> users, Set<Carrequisitionservice> carrequisitionservices, Set<Officeassetrequisition> officeassetrequisitions, Set<Requisitionresponses> requisitionresponsesesForHodEmployeeRegistrationId, Set<Stationaryregistration> stationaryregistrations, Set<Stationaryrequisition> stationaryrequisitions, Set<User> users_1, Set<Carrequisitionservice> carrequisitionservices_1, Set<Officeassetrequisition> officeassetrequisitions_1, Set<Carrequisition> carrequisitions, Set<Requisitionresponses> requisitionresponsesesForLogisticEmployeeRegistrationId, Set<Carrequisition> carrequisitions_1, Set<Stationaryrequisition> stationaryrequisitions_1, Set<Requisitionresponses> requisitionresponsesesForDafEmployeeRegistrationId) {
       this.department = department;
       this.employeeCode = employeeCode;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.jobPosition = jobPosition;
       this.nationalId = nationalId;
       this.telephone = telephone;
       this.identificationWord = identificationWord;
       this.state = state;
       this.firstDate = firstDate;
       this.changePositionDate = changePositionDate;
       this.innactiveDate = innactiveDate;
       this.driver = driver;
       this.licenceNumber = licenceNumber;
       this.workEmail = workEmail;
       this.users = users;
       this.carrequisitionservices = carrequisitionservices;
       this.officeassetrequisitions = officeassetrequisitions;
       this.requisitionresponsesesForHodEmployeeRegistrationId = requisitionresponsesesForHodEmployeeRegistrationId;
       this.stationaryregistrations = stationaryregistrations;
       this.stationaryrequisitions = stationaryrequisitions;
       this.users_1 = users_1;
       this.carrequisitionservices_1 = carrequisitionservices_1;
       this.officeassetrequisitions_1 = officeassetrequisitions_1;
       this.carrequisitions = carrequisitions;
       this.requisitionresponsesesForLogisticEmployeeRegistrationId = requisitionresponsesesForLogisticEmployeeRegistrationId;
       this.carrequisitions_1 = carrequisitions_1;
       this.stationaryrequisitions_1 = stationaryrequisitions_1;
       this.requisitionresponsesesForDafEmployeeRegistrationId = requisitionresponsesesForDafEmployeeRegistrationId;
    }
   
    public Integer getEmployeeRegistrationId() {
        return this.employeeRegistrationId;
    }
    
    public void setEmployeeRegistrationId(Integer employeeRegistrationId) {
        this.employeeRegistrationId = employeeRegistrationId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getJobPosition() {
        return this.jobPosition;
    }
    
    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }
    public String getNationalId() {
        return this.nationalId;
    }
    
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getIdentificationWord() {
        return this.identificationWord;
    }
    
    public void setIdentificationWord(String identificationWord) {
        this.identificationWord = identificationWord;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Date getFirstDate() {
        return this.firstDate;
    }
    
    public void setFirstDate(Date firstDate) {
        this.firstDate = firstDate;
    }
    public Date getChangePositionDate() {
        return this.changePositionDate;
    }
    
    public void setChangePositionDate(Date changePositionDate) {
        this.changePositionDate = changePositionDate;
    }
    public Date getInnactiveDate() {
        return this.innactiveDate;
    }
    
    public void setInnactiveDate(Date innactiveDate) {
        this.innactiveDate = innactiveDate;
    }
    public Boolean getDriver() {
        return this.driver;
    }
    
    public void setDriver(Boolean driver) {
        this.driver = driver;
    }
    public String getLicenceNumber() {
        return this.licenceNumber;
    }
    
    public void setLicenceNumber(String licenceNumber) {
        this.licenceNumber = licenceNumber;
    }
    public String getWorkEmail() {
        return this.workEmail;
    }
    
    public void setWorkEmail(String workEmail) {
        this.workEmail = workEmail;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Carrequisitionservice> getCarrequisitionservices() {
        return this.carrequisitionservices;
    }
    
    public void setCarrequisitionservices(Set<Carrequisitionservice> carrequisitionservices) {
        this.carrequisitionservices = carrequisitionservices;
    }
    public Set<Officeassetrequisition> getOfficeassetrequisitions() {
        return this.officeassetrequisitions;
    }
    
    public void setOfficeassetrequisitions(Set<Officeassetrequisition> officeassetrequisitions) {
        this.officeassetrequisitions = officeassetrequisitions;
    }
    public Set<Requisitionresponses> getRequisitionresponsesesForHodEmployeeRegistrationId() {
        return this.requisitionresponsesesForHodEmployeeRegistrationId;
    }
    
    public void setRequisitionresponsesesForHodEmployeeRegistrationId(Set<Requisitionresponses> requisitionresponsesesForHodEmployeeRegistrationId) {
        this.requisitionresponsesesForHodEmployeeRegistrationId = requisitionresponsesesForHodEmployeeRegistrationId;
    }
    public Set<Stationaryregistration> getStationaryregistrations() {
        return this.stationaryregistrations;
    }
    
    public void setStationaryregistrations(Set<Stationaryregistration> stationaryregistrations) {
        this.stationaryregistrations = stationaryregistrations;
    }
    public Set<Stationaryrequisition> getStationaryrequisitions() {
        return this.stationaryrequisitions;
    }
    
    public void setStationaryrequisitions(Set<Stationaryrequisition> stationaryrequisitions) {
        this.stationaryrequisitions = stationaryrequisitions;
    }
    public Set<User> getUsers_1() {
        return this.users_1;
    }
    
    public void setUsers_1(Set<User> users_1) {
        this.users_1 = users_1;
    }
    public Set<Carrequisitionservice> getCarrequisitionservices_1() {
        return this.carrequisitionservices_1;
    }
    
    public void setCarrequisitionservices_1(Set<Carrequisitionservice> carrequisitionservices_1) {
        this.carrequisitionservices_1 = carrequisitionservices_1;
    }
    public Set<Officeassetrequisition> getOfficeassetrequisitions_1() {
        return this.officeassetrequisitions_1;
    }
    
    public void setOfficeassetrequisitions_1(Set<Officeassetrequisition> officeassetrequisitions_1) {
        this.officeassetrequisitions_1 = officeassetrequisitions_1;
    }
    public Set<Carrequisition> getCarrequisitions() {
        return this.carrequisitions;
    }
    
    public void setCarrequisitions(Set<Carrequisition> carrequisitions) {
        this.carrequisitions = carrequisitions;
    }
    public Set<Requisitionresponses> getRequisitionresponsesesForLogisticEmployeeRegistrationId() {
        return this.requisitionresponsesesForLogisticEmployeeRegistrationId;
    }
    
    public void setRequisitionresponsesesForLogisticEmployeeRegistrationId(Set<Requisitionresponses> requisitionresponsesesForLogisticEmployeeRegistrationId) {
        this.requisitionresponsesesForLogisticEmployeeRegistrationId = requisitionresponsesesForLogisticEmployeeRegistrationId;
    }
    public Set<Carrequisition> getCarrequisitions_1() {
        return this.carrequisitions_1;
    }
    
    public void setCarrequisitions_1(Set<Carrequisition> carrequisitions_1) {
        this.carrequisitions_1 = carrequisitions_1;
    }
    public Set<Stationaryrequisition> getStationaryrequisitions_1() {
        return this.stationaryrequisitions_1;
    }
    
    public void setStationaryrequisitions_1(Set<Stationaryrequisition> stationaryrequisitions_1) {
        this.stationaryrequisitions_1 = stationaryrequisitions_1;
    }
    public Set<Requisitionresponses> getRequisitionresponsesesForDafEmployeeRegistrationId() {
        return this.requisitionresponsesesForDafEmployeeRegistrationId;
    }
    
    public void setRequisitionresponsesesForDafEmployeeRegistrationId(Set<Requisitionresponses> requisitionresponsesesForDafEmployeeRegistrationId) {
        this.requisitionresponsesesForDafEmployeeRegistrationId = requisitionresponsesesForDafEmployeeRegistrationId;
    }




}


