package jim.omerspi.model;
// Generated Jun 6, 2013 3:43:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Itenerary generated by hbm2java
 */
public class Itenerary  implements java.io.Serializable {


     private Integer iteneraryId;
     private String iteneraryDetail;
     private Integer cost;
     private Set<Carrequisition> carrequisitions = new HashSet<Carrequisition>(0);

    public Itenerary() {
    }

	
    public Itenerary(String iteneraryDetail) {
        this.iteneraryDetail = iteneraryDetail;
    }
    public Itenerary(String iteneraryDetail, Integer cost, Set<Carrequisition> carrequisitions) {
       this.iteneraryDetail = iteneraryDetail;
       this.cost = cost;
       this.carrequisitions = carrequisitions;
    }
   
    public Integer getIteneraryId() {
        return this.iteneraryId;
    }
    
    public void setIteneraryId(Integer iteneraryId) {
        this.iteneraryId = iteneraryId;
    }
    public String getIteneraryDetail() {
        return this.iteneraryDetail;
    }
    
    public void setIteneraryDetail(String iteneraryDetail) {
        this.iteneraryDetail = iteneraryDetail;
    }
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }
    public Set<Carrequisition> getCarrequisitions() {
        return this.carrequisitions;
    }
    
    public void setCarrequisitions(Set<Carrequisition> carrequisitions) {
        this.carrequisitions = carrequisitions;
    }




}


