package jim.omerspi.model;
// Generated Sep 2, 2013 11:37:18 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Memo generated by hbm2java
 */
public class Memo  implements java.io.Serializable {


     private Integer memoId;
     private Officeassetrequisition officeassetrequisition;
     private Carrequisition carrequisition;
     private String sendTo;
     private String cc;
     private Date dueDate;
     private String subject;

    public Memo() {
    }

    public Memo(Officeassetrequisition officeassetrequisition, Carrequisition carrequisition, String sendTo, String cc, Date dueDate, String subject) {
       this.officeassetrequisition = officeassetrequisition;
       this.carrequisition = carrequisition;
       this.sendTo = sendTo;
       this.cc = cc;
       this.dueDate = dueDate;
       this.subject = subject;
    }
   
    public Integer getMemoId() {
        return this.memoId;
    }
    
    public void setMemoId(Integer memoId) {
        this.memoId = memoId;
    }
    public Officeassetrequisition getOfficeassetrequisition() {
        return this.officeassetrequisition;
    }
    
    public void setOfficeassetrequisition(Officeassetrequisition officeassetrequisition) {
        this.officeassetrequisition = officeassetrequisition;
    }
    public Carrequisition getCarrequisition() {
        return this.carrequisition;
    }
    
    public void setCarrequisition(Carrequisition carrequisition) {
        this.carrequisition = carrequisition;
    }
    public String getSendTo() {
        return this.sendTo;
    }
    
    public void setSendTo(String sendTo) {
        this.sendTo = sendTo;
    }
    public String getCc() {
        return this.cc;
    }
    
    public void setCc(String cc) {
        this.cc = cc;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }




}


