package jim.omerspi.model;
// Generated Sep 3, 2013 1:38:04 PM by Hibernate Tools 3.2.1.GA

/**
 * Officeassetrequisitionservice generated by hbm2java
 */
public class Officeassetrequisitionservice implements java.io.Serializable {

    private Integer serviceId;
    private RequestedItems requestedItems;
    private String serialNumber;
    private String officeAssetCode;
    private String observation;

    public Officeassetrequisitionservice() {
    }

    public Officeassetrequisitionservice(RequestedItems requestedItems) {
        this.requestedItems = requestedItems;
    }

    public Officeassetrequisitionservice(RequestedItems requestedItems, String serialNumber, String officeAssetCode, String observation) {
        this.requestedItems = requestedItems;
        this.serialNumber = serialNumber;
        this.officeAssetCode = officeAssetCode;
        this.observation = observation;
    }

    public Integer getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    public RequestedItems getRequestedItems() {
        return this.requestedItems;
    }

    public void setRequestedItems(RequestedItems requestedItems) {
        this.requestedItems = requestedItems;
    }

    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getOfficeAssetCode() {
        return this.officeAssetCode;
    }

    public void setOfficeAssetCode(String officeAssetCode) {
        this.officeAssetCode = officeAssetCode;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }    
}
