package jim.omerspi.model;
// Generated Sep 2, 2013 11:37:18 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Officeassetrequisition generated by hbm2java
 */
public class Officeassetrequisition implements java.io.Serializable {

    private Integer officeAssetRequisitionId;
    private Employee employee;
    private String beneficiary;
    private String roomNumber;
    private Date requisitionDate;
    private Date serviceDate;
    private String serviceNumber;
    private String status;
    private boolean officeRequisitionSeen;
    private Set<Memo> memos = new HashSet<Memo>(0);
    private Set<Memo> memos_1 = new HashSet<Memo>(0);
    private Set<Requisitionresponses> requisitionresponseses = new HashSet<Requisitionresponses>(0);
    private Set<RequestedItems> requestedItemses = new HashSet<RequestedItems>(0);

    public Officeassetrequisition() {
    }

    public Officeassetrequisition(Employee employee, String roomNumber, Date requisitionDate, String status, boolean officeRequisitionSeen) {
        this.employee = employee;
        this.roomNumber = roomNumber;
        this.requisitionDate = requisitionDate;
        this.status = status;
        this.officeRequisitionSeen = officeRequisitionSeen;
    }

    public Officeassetrequisition(Employee employee, String beneficiary, String roomNumber, Date requisitionDate, Date serviceDate, String serviceNumber, String status, boolean officeRequisitionSeen, Set<Memo> memos, Set<Memo> memos_1, Set<Requisitionresponses> requisitionresponseses, Set<RequestedItems> requestedItemses) {
        this.employee = employee;
        this.beneficiary = beneficiary;
        this.roomNumber = roomNumber;
        this.requisitionDate = requisitionDate;
        this.serviceDate = serviceDate;
        this.serviceNumber = serviceNumber;
        this.status = status;
        this.officeRequisitionSeen = officeRequisitionSeen;
        this.memos = memos;
        this.memos_1 = memos_1;
        this.requisitionresponseses = requisitionresponseses;
        this.requestedItemses = requestedItemses;
    }

    public Integer getOfficeAssetRequisitionId() {
        return this.officeAssetRequisitionId;
    }

    public void setOfficeAssetRequisitionId(Integer officeAssetRequisitionId) {
        this.officeAssetRequisitionId = officeAssetRequisitionId;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public String getBeneficiary() {
        return beneficiary;
    }

    public void setBeneficiary(String beneficiary) {
        this.beneficiary = beneficiary;
    }

    public String getRoomNumber() {
        return this.roomNumber;
    }

    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    public Date getRequisitionDate() {
        return this.requisitionDate;
    }

    public void setRequisitionDate(Date requisitionDate) {
        this.requisitionDate = requisitionDate;
    }

    public Date getServiceDate() {
        return this.serviceDate;
    }

    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }

    public String getServiceNumber() {
        return this.serviceNumber;
    }

    public void setServiceNumber(String serviceNumber) {
        this.serviceNumber = serviceNumber;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public boolean isOfficeRequisitionSeen() {
        return this.officeRequisitionSeen;
    }

    public void setOfficeRequisitionSeen(boolean officeRequisitionSeen) {
        this.officeRequisitionSeen = officeRequisitionSeen;
    }

    public Set<Memo> getMemos() {
        return this.memos;
    }

    public void setMemos(Set<Memo> memos) {
        this.memos = memos;
    }

    public Set<Memo> getMemos_1() {
        return this.memos_1;
    }

    public void setMemos_1(Set<Memo> memos_1) {
        this.memos_1 = memos_1;
    }

    public Set<Requisitionresponses> getRequisitionresponseses() {
        return this.requisitionresponseses;
    }

    public void setRequisitionresponseses(Set<Requisitionresponses> requisitionresponseses) {
        this.requisitionresponseses = requisitionresponseses;
    }

    public Set<RequestedItems> getRequestedItemses() {
        return requestedItemses;
    }

    public void setRequestedItemses(Set<RequestedItems> requestedItemses) {
        this.requestedItemses = requestedItemses;
    }
}
