package jim.omerspi.model;
// Generated May 14, 2013 4:28:15 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege implements java.io.Serializable {

    private String privilege;
    private String previlageDescription;
    private Set<Role> roles = new HashSet<Role>(0);

    public Privilege() {
    }

    public Privilege(String privilege, String previlageDescription) {
        this.privilege = privilege;
        this.previlageDescription = previlageDescription;
    }

    public Privilege(String privilege, String previlageDescription, Set<Role> roles) {
        this.privilege = privilege;
        this.previlageDescription = previlageDescription;
        this.roles = roles;
    }

    public String getPrivilege() {
        return this.privilege;
    }

    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    public String getPrevilageDescription() {
        return this.previlageDescription;
    }

    public void setPrevilageDescription(String previlageDescription) {
        this.previlageDescription = previlageDescription;
    }

    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
}
