package jim.omerspi.model;
// Generated Sep 2, 2013 11:37:18 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Requisitionresponses generated by hbm2java
 */
public class Requisitionresponses  implements java.io.Serializable {


     private Integer requisitionResponseId;
     private Employee employeeByHodEmployeeRegistrationId;
     private Officeassetrequisition officeassetrequisition;
     private Employee employeeByDafEmployeeRegistrationId;
     private Stationaryrequisition stationaryrequisition;
     private Carrequisition carrequisition;
     private Employee employeeByLogisticEmployeeRegistrationId;
     private String hodResponse;
     private Date hodResponseDate;
     private String hodComment;
     private String dafResponse;
     private String dafComment;
     private Date dafResponseDate;
     private String logisticComment;

    public Requisitionresponses() {
    }

    public Requisitionresponses(Employee employeeByHodEmployeeRegistrationId, Officeassetrequisition officeassetrequisition, Employee employeeByDafEmployeeRegistrationId, Stationaryrequisition stationaryrequisition, Carrequisition carrequisition, Employee employeeByLogisticEmployeeRegistrationId, String hodResponse, Date hodResponseDate, String hodComment, String dafResponse, String dafComment, Date dafResponseDate, String logisticComment) {
       this.employeeByHodEmployeeRegistrationId = employeeByHodEmployeeRegistrationId;
       this.officeassetrequisition = officeassetrequisition;
       this.employeeByDafEmployeeRegistrationId = employeeByDafEmployeeRegistrationId;
       this.stationaryrequisition = stationaryrequisition;
       this.carrequisition = carrequisition;
       this.employeeByLogisticEmployeeRegistrationId = employeeByLogisticEmployeeRegistrationId;
       this.hodResponse = hodResponse;
       this.hodResponseDate = hodResponseDate;
       this.hodComment = hodComment;
       this.dafResponse = dafResponse;
       this.dafComment = dafComment;
       this.dafResponseDate = dafResponseDate;
       this.logisticComment = logisticComment;
    }
   
    public Integer getRequisitionResponseId() {
        return this.requisitionResponseId;
    }
    
    public void setRequisitionResponseId(Integer requisitionResponseId) {
        this.requisitionResponseId = requisitionResponseId;
    }
    public Employee getEmployeeByHodEmployeeRegistrationId() {
        return this.employeeByHodEmployeeRegistrationId;
    }
    
    public void setEmployeeByHodEmployeeRegistrationId(Employee employeeByHodEmployeeRegistrationId) {
        this.employeeByHodEmployeeRegistrationId = employeeByHodEmployeeRegistrationId;
    }
    public Officeassetrequisition getOfficeassetrequisition() {
        return this.officeassetrequisition;
    }
    
    public void setOfficeassetrequisition(Officeassetrequisition officeassetrequisition) {
        this.officeassetrequisition = officeassetrequisition;
    }
    public Employee getEmployeeByDafEmployeeRegistrationId() {
        return this.employeeByDafEmployeeRegistrationId;
    }
    
    public void setEmployeeByDafEmployeeRegistrationId(Employee employeeByDafEmployeeRegistrationId) {
        this.employeeByDafEmployeeRegistrationId = employeeByDafEmployeeRegistrationId;
    }
    public Stationaryrequisition getStationaryrequisition() {
        return this.stationaryrequisition;
    }
    
    public void setStationaryrequisition(Stationaryrequisition stationaryrequisition) {
        this.stationaryrequisition = stationaryrequisition;
    }
    public Carrequisition getCarrequisition() {
        return this.carrequisition;
    }
    
    public void setCarrequisition(Carrequisition carrequisition) {
        this.carrequisition = carrequisition;
    }
    public Employee getEmployeeByLogisticEmployeeRegistrationId() {
        return this.employeeByLogisticEmployeeRegistrationId;
    }
    
    public void setEmployeeByLogisticEmployeeRegistrationId(Employee employeeByLogisticEmployeeRegistrationId) {
        this.employeeByLogisticEmployeeRegistrationId = employeeByLogisticEmployeeRegistrationId;
    }
    public String getHodResponse() {
        return this.hodResponse;
    }
    
    public void setHodResponse(String hodResponse) {
        this.hodResponse = hodResponse;
    }
    public Date getHodResponseDate() {
        return this.hodResponseDate;
    }
    
    public void setHodResponseDate(Date hodResponseDate) {
        this.hodResponseDate = hodResponseDate;
    }
    public String getHodComment() {
        return this.hodComment;
    }
    
    public void setHodComment(String hodComment) {
        this.hodComment = hodComment;
    }
    public String getDafResponse() {
        return this.dafResponse;
    }
    
    public void setDafResponse(String dafResponse) {
        this.dafResponse = dafResponse;
    }
    public String getDafComment() {
        return this.dafComment;
    }
    
    public void setDafComment(String dafComment) {
        this.dafComment = dafComment;
    }
    public Date getDafResponseDate() {
        return this.dafResponseDate;
    }
    
    public void setDafResponseDate(Date dafResponseDate) {
        this.dafResponseDate = dafResponseDate;
    }
    public String getLogisticComment() {
        return this.logisticComment;
    }
    
    public void setLogisticComment(String logisticComment) {
        this.logisticComment = logisticComment;
    }




}


