package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RequestedItems generated by hbm2java
 */
public class RequestedItems implements java.io.Serializable {

    private Integer requestedId;
    private Stationaryrequisition stationaryrequisition;
    private Officeassetrequisition officeassetrequisition;
    private Items items;
    private int requestedQty;
    private Integer servedQty;
    private String observation;
    private Integer remainingQty;
    private Date serviceDate;
    private Set<Officeassetrequisitionservice> officeassetrequisitionservices = new HashSet<Officeassetrequisitionservice>(0);

    public RequestedItems() {
    }

    public RequestedItems(Items items, int requestedQty) {
        this.items = items;
        this.requestedQty = requestedQty;
    }

    public RequestedItems(Stationaryrequisition stationaryrequisition, Officeassetrequisition officeassetrequisition, Items items, int requestedQty, Integer servedQty, String observation, Integer remainingQty, Date serviceDate, Set<Officeassetrequisitionservice> officeassetrequisitionservices) {
        this.stationaryrequisition = stationaryrequisition;
        this.officeassetrequisition = officeassetrequisition;
        this.items = items;
        this.requestedQty = requestedQty;
        this.servedQty = servedQty;
        this.observation = observation;
        this.remainingQty = remainingQty;
        this.serviceDate = serviceDate;
        this.officeassetrequisitionservices = officeassetrequisitionservices;
    }

    public Integer getRequestedId() {
        return this.requestedId;
    }

    public void setRequestedId(Integer requestedId) {
        this.requestedId = requestedId;
    }

    public Stationaryrequisition getStationaryrequisition() {
        return this.stationaryrequisition;
    }

    public void setStationaryrequisition(Stationaryrequisition stationaryrequisition) {
        this.stationaryrequisition = stationaryrequisition;
    }

    public Officeassetrequisition getOfficeassetrequisition() {
        return officeassetrequisition;
    }

    public void setOfficeassetrequisition(Officeassetrequisition officeassetrequisition) {
        this.officeassetrequisition = officeassetrequisition;
    }

    public Items getItems() {
        return this.items;
    }

    public void setItems(Items items) {
        this.items = items;
    }

    public int getRequestedQty() {
        return this.requestedQty;
    }

    public void setRequestedQty(int requestedQty) {
        this.requestedQty = requestedQty;
    }

    public Integer getServedQty() {
        return this.servedQty;
    }

    public void setServedQty(Integer servedQty) {
        this.servedQty = servedQty;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Integer getRemainingQty() {
        return this.remainingQty;
    }

    public void setRemainingQty(Integer remainingQty) {
        this.remainingQty = remainingQty;
    }

    public Date getServiceDate() {
        return this.serviceDate;
    }

    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }

    public Set<Officeassetrequisitionservice> getOfficeassetrequisitionservices() {
        return officeassetrequisitionservices;
    }

    public void setOfficeassetrequisitionservices(Set<Officeassetrequisitionservice> officeassetrequisitionservices) {
        this.officeassetrequisitionservices = officeassetrequisitionservices;
    }
}
