package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Stationaryregistration generated by hbm2java
 */
public class Stationaryregistration implements java.io.Serializable {

    private Integer stationaryRegistrationId;
    private Vendor vendor;
    private Employee employee;
    private Items items;
    private String purchaseOrder;
    private String deliveryNoteNumber;
    private String contractNumber;
    private String specification;
    private int purchasedQty;
    private int unitPrice;
    private Date acquisitionDate;
    private Date modifiedOn;
    private int openingStock;

    public Stationaryregistration() {
    }

    public Stationaryregistration(Vendor vendor, Employee employee, Items items, String deliveryNoteNumber, String contractNumber, String specification, int purchasedQty, int unitPrice, Date acquisitionDate) {
        this.vendor = vendor;
        this.employee = employee;
        this.items = items;
        this.deliveryNoteNumber = deliveryNoteNumber;
        this.contractNumber = contractNumber;
        this.specification = specification;
        this.purchasedQty = purchasedQty;
        this.unitPrice = unitPrice;
        this.acquisitionDate = acquisitionDate;
    }

    public Stationaryregistration(Vendor vendor, Employee employee, Items items, String purchaseOrder, String deliveryNoteNumber, String contractNumber, String specification, int purchasedQty, int unitPrice, Date acquisitionDate, Date modifiedOn, int openingStock) {
        this.vendor = vendor;
        this.employee = employee;
        this.items = items;
        this.purchaseOrder = purchaseOrder;
        this.deliveryNoteNumber = deliveryNoteNumber;
        this.contractNumber = contractNumber;
        this.specification = specification;
        this.purchasedQty = purchasedQty;
        this.unitPrice = unitPrice;
        this.acquisitionDate = acquisitionDate;
        this.modifiedOn = modifiedOn;
        this.openingStock = openingStock;
    }

    public Integer getStationaryRegistrationId() {
        return this.stationaryRegistrationId;
    }

    public void setStationaryRegistrationId(Integer stationaryRegistrationId) {
        this.stationaryRegistrationId = stationaryRegistrationId;
    }

    public Vendor getVendor() {
        return this.vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Items getItems() {
        return this.items;
    }

    public void setItems(Items items) {
        this.items = items;
    }

    public String getPurchaseOrder() {
        return this.purchaseOrder;
    }

    public void setPurchaseOrder(String purchaseOrder) {
        this.purchaseOrder = purchaseOrder;
    }

    public String getDeliveryNoteNumber() {
        return this.deliveryNoteNumber;
    }

    public void setDeliveryNoteNumber(String deliveryNoteNumber) {
        this.deliveryNoteNumber = deliveryNoteNumber;
    }

    public String getContractNumber() {
        return this.contractNumber;
    }

    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    public String getSpecification() {
        return this.specification;
    }

    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public int getPurchasedQty() {
        return this.purchasedQty;
    }

    public void setPurchasedQty(int purchasedQty) {
        this.purchasedQty = purchasedQty;
    }

    public int getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(int unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Date getAcquisitionDate() {
        return this.acquisitionDate;
    }

    public void setAcquisitionDate(Date acquisitionDate) {
        this.acquisitionDate = acquisitionDate;
    }

    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    public int getOpeningStock() {
        return openingStock;
    }

    public void setOpeningStock(int openingStock) {
        this.openingStock = openingStock;
    }
}
