package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stationaryrequisition generated by hbm2java
 */
public class Stationaryrequisition  implements java.io.Serializable {


     private Integer stationaryRequisitionId;
     private Employee employee;
     private Date requisitionDate;
     private Date serviceDate;
     private String status;
     private String serviceNumber;
     private Boolean stationarySeen;
     private Set<Requisitionresponses> requisitionresponseses = new HashSet<Requisitionresponses>(0);
     private Set<RequestedItems> requestedItemses = new HashSet<RequestedItems>(0);

    public Stationaryrequisition() {
    }

	
    public Stationaryrequisition(Employee employee, Date requisitionDate) {
        this.employee = employee;
        this.requisitionDate = requisitionDate;
    }
    public Stationaryrequisition(Employee employee, Date requisitionDate, Date serviceDate, String status, String serviceNumber, Boolean stationarySeen, Set<Requisitionresponses> requisitionresponseses, Set<RequestedItems> requestedItemses) {
       this.employee = employee;
       this.requisitionDate = requisitionDate;
       this.serviceDate = serviceDate;
       this.status = status;
       this.serviceNumber = serviceNumber;
       this.stationarySeen = stationarySeen;
       this.requisitionresponseses = requisitionresponseses;
       this.requestedItemses = requestedItemses;
    }
   
    public Integer getStationaryRequisitionId() {
        return this.stationaryRequisitionId;
    }
    
    public void setStationaryRequisitionId(Integer stationaryRequisitionId) {
        this.stationaryRequisitionId = stationaryRequisitionId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getRequisitionDate() {
        return this.requisitionDate;
    }
    
    public void setRequisitionDate(Date requisitionDate) {
        this.requisitionDate = requisitionDate;
    }
    public Date getServiceDate() {
        return this.serviceDate;
    }
    
    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getServiceNumber() {
        return this.serviceNumber;
    }
    
    public void setServiceNumber(String serviceNumber) {
        this.serviceNumber = serviceNumber;
    }
    public Boolean getStationarySeen() {
        return this.stationarySeen;
    }
    
    public void setStationarySeen(Boolean stationarySeen) {
        this.stationarySeen = stationarySeen;
    }
    public Set<Requisitionresponses> getRequisitionresponseses() {
        return this.requisitionresponseses;
    }
    
    public void setRequisitionresponseses(Set<Requisitionresponses> requisitionresponseses) {
        this.requisitionresponseses = requisitionresponseses;
    }
    public Set<RequestedItems> getRequestedItemses() {
        return this.requestedItemses;
    }
    
    public void setRequestedItemses(Set<RequestedItems> requestedItemses) {
        this.requestedItemses = requestedItemses;
    }




}


