package jim.omerspi.model;
// Generated May 14, 2013 4:28:15 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer userRegistrationId;
    private Employee employee;
    private String userName;
    private String password;
    private Date lastLoginTime;
    private Set<Role> roles = new HashSet<Role>(0);
    private Set<Role> roles_1 = new HashSet<Role>(0);

    public User() {
    }

    public User(Employee employee, String userName, String password) {
        this.employee = employee;
        this.userName = userName;
        this.password = password;
    }

    public User(Employee employee, String userName, String password, Date lastLoginTime, Set<Role> roles, Set<Role> roles_1) {
        this.employee = employee;
        this.userName = userName;
        this.password = password;
        this.lastLoginTime = lastLoginTime;
        this.roles = roles;
        this.roles_1 = roles_1;
    }

    public boolean isSuperUser() {

        for (Role role : roles) {
            if (role.isSuperUser()) {
                return true;
            }
        }
        return false;
    }

    public boolean hasPrivilege(String privilege) {

        for (Role role : roles) {
            if (role.hasPrivilege(privilege)) {
                return true;
            }
        }
        return false;
    }

    public Integer getUserRegistrationId() {
        return this.userRegistrationId;
    }

    public void setUserRegistrationId(Integer userRegistrationId) {
        this.userRegistrationId = userRegistrationId;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public Set<Role> getRoles_1() {
        return this.roles_1;
    }

    public void setRoles_1(Set<Role> roles_1) {
        this.roles_1 = roles_1;
    }
}
