package jim.omerspi.model;
// Generated Sep 1, 2013 10:25:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private Integer vendorRegistrationId;
     private String vendorName;
     private String address;
     private String email;
     private String telephone;
     private String tenderNumber;
     private String tenderPurpose;
     private Date startingPeriod;
     private Date endingPeriod;
     private Set<Carrequisitionservice> carrequisitionservices = new HashSet<Carrequisitionservice>(0);
     private Set<Stationaryregistration> stationaryregistrations = new HashSet<Stationaryregistration>(0);

    public Vendor() {
    }

	
    public Vendor(String vendorName, String address, String tenderNumber) {
        this.vendorName = vendorName;
        this.address = address;
        this.tenderNumber = tenderNumber;
    }
    public Vendor(String vendorName, String address, String email, String telephone, String tenderNumber, String tenderPurpose, Date startingPeriod, Date endingPeriod, Set<Carrequisitionservice> carrequisitionservices, Set<Stationaryregistration> stationaryregistrations) {
       this.vendorName = vendorName;
       this.address = address;
       this.email = email;
       this.telephone = telephone;
       this.tenderNumber = tenderNumber;
       this.tenderPurpose = tenderPurpose;
       this.startingPeriod = startingPeriod;
       this.endingPeriod = endingPeriod;
       this.carrequisitionservices = carrequisitionservices;
       this.stationaryregistrations = stationaryregistrations;
    }
   
    public Integer getVendorRegistrationId() {
        return this.vendorRegistrationId;
    }
    
    public void setVendorRegistrationId(Integer vendorRegistrationId) {
        this.vendorRegistrationId = vendorRegistrationId;
    }
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getTenderNumber() {
        return this.tenderNumber;
    }
    
    public void setTenderNumber(String tenderNumber) {
        this.tenderNumber = tenderNumber;
    }
    public String getTenderPurpose() {
        return this.tenderPurpose;
    }
    
    public void setTenderPurpose(String tenderPurpose) {
        this.tenderPurpose = tenderPurpose;
    }
    public Date getStartingPeriod() {
        return this.startingPeriod;
    }
    
    public void setStartingPeriod(Date startingPeriod) {
        this.startingPeriod = startingPeriod;
    }
    public Date getEndingPeriod() {
        return this.endingPeriod;
    }
    
    public void setEndingPeriod(Date endingPeriod) {
        this.endingPeriod = endingPeriod;
    }
    public Set<Carrequisitionservice> getCarrequisitionservices() {
        return this.carrequisitionservices;
    }
    
    public void setCarrequisitionservices(Set<Carrequisitionservice> carrequisitionservices) {
        this.carrequisitionservices = carrequisitionservices;
    }
    public Set<Stationaryregistration> getStationaryregistrations() {
        return this.stationaryregistrations;
    }
    
    public void setStationaryregistrations(Set<Stationaryregistration> stationaryregistrations) {
        this.stationaryregistrations = stationaryregistrations;
    }




}


